- hosts: web #グループ名
  gather_facts: False
  remote_user: ec2-user

  vars_prompt:
  - name: setup_httpd
    prompt: "Do you setup Webserver ?"
    private: no
    default: Y

  tasks:
    - name: Yum install httpd
      yum: name=httpd state=latest
      notify:
      - service_httpd_start
      when: setup_httpd == "Y"

  handlers:
    - name: service_httpd_start
      service: name=httpd state=started
